[package]
name = "chainscan"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.10.0"
solana-program = "2.0.11"
bincode = "1.3.3"
rand = "0.8"  # Using the rand crate instead of getrandom
